

TCLSRC=				\
	camera.tcl		\
	wavefront.tcl		\
	axis_control.tcl	\
	axis_tweak.tcl		\
	axis_plot.tcl		\
	mstatus.tcl


wavedisplay: $(TCLSRC)
	xinc wavefront.tcl > wavedisplay

install: 
	cp wavedisplay /data/mmti/bin/.
