#!/usr/bin/ruby

require 'gtk2'

mainWindow = Gtk::Window.new
mainWindow.signal_connect('destroy') { Gtk::main_quit }
str = Time.now.strftime('Today is %B %d, %Y')
mainWindow.add( Gtk::Label.new(str) )
mainWindow.set_default_size(200, 100)
mainWindow.show_all
Gtk::main
