#!/usr/bin/ruby

# this was updated on 11-10-05 after an elcoll run

require 'timeout'
require 'socket'
require '/mmt/shwfs/msg.rb'

include Math
include MSG

zeropoint = Hash.new
#zeropoint['hecto'] = 13977
#zeropoint['hecto'] = 13913
#zeropoint['hecto'] = 13398
# <20061003
#zeropoint['hecto'] = 13204
#zeropoint['megacam'] = 12949
#zeropoint['swirc'] = 8588
zeropoint['hecto'] = 13088
zeropoint['megacam'] = 12708
zeropoint['swirc'] = 8403

config = case ARGV[0]
	   when /megacam/i then "megacam"
	   when /hecto/i then "hecto"
	   when /swirc/i then "swirc"
	   when /f9/i then "f9"
	 else 
	   puts "Usage: hex_predict <megacam|hecto|swirc|f9>"
	   exit
	 end

hexapod = sockopen('hexapod', 5350)
telserver = sockopen('hacksaw', 5403)

focus = msg_get(hexapod, 'focus').to_f
tiltx = msg_get(hexapod, 'tiltx').to_f
tilty = msg_get(hexapod, 'tilty').to_f
transx = msg_get(hexapod, 'transx').to_f
transy = msg_get(hexapod, 'transy').to_f
temp = msg_get(hexapod, 'curr_temp').to_f
el_deg = msg_get(telserver, 'el').to_f

el = el_deg*PI/180.0

temps = `/mmt/shwfs/getOSStemps`.split(' ')

temp = ( (temps[0].to_f + temps[1].to_f + temps[2].to_f + temps[3].to_f)/4.0 + (temps[4].to_f + temps[5].to_f)/2.0 )/2.0

if (el < 0 || temp < -50) 
  puts "El or Temp is Bogus."
  exit
end

puts "Hexapod is at:"
puts "   focus = #{focus},"
puts "   tiltx = #{tiltx},"
puts "   tilty = #{tilty},"
puts "   transx = #{transx},"
puts "   transy = #{transy}"
puts "Telescope is at: El = #{el_deg}, OSS Temp = #{temp} C"

if config == "f9"
  pred_focus  =   950.1*cos(el) + 1862.0*sin(el) - 46.7*temp -  900.0
  pred_tiltx  =  -143.0*cos(el) -  388.8*sin(el) + 0.16*temp +  540.0
  pred_tilty  =   186.5*cos(el) +  234.0*sin(el) - 0.50*temp -  179.4
  pred_transx = -1308.7*cos(el) - 1820.2*sin(el) - 1.70*temp + 2545.4 
  pred_transy =   -39.5*cos(el) - 1623.3*sin(el) - 7.00*temp + 1184.5
else
  pred_focus = zeropoint[config] - 35.3*(temp-10.4) + 1277.21*sin(el) + 230.27*cos(el)

  # from fall 2005
  #pred_tiltx = 324.350 + 28.184*sin(el) + 195.598*cos(el)
  #pred_tilty = 44.123 + 4.342*sin(el) + 37.722*cos(el) - 2.5*(temp-10.4)
  #pred_transx = -265.387 + 81.523*sin(el) - 381.418*cos(el) - 8.6*(temp-10.4)
  #pred_transy = 1220.929 + 969.577*sin(el) + 2050.295*cos(el)

  # from megacam 20060103
  #pred_tilty = 79.3364*sin(el) + 49.4663*cos(el) + 0.2188*temp + 28.029
  #pred_transx = -481.355*sin(el) - 245.984*cos(el) - 16.6192*temp - 171.433
  #pred_transy = -356.485*sin(el) + 1515.93*cos(el) + 115.356*temp + 989.48
  #pred_tiltx = 14.3645*sin(el) + 201.84*cos(el) + 0.08*temp + 283.358

  # from hecto 20060314
  #pred_tilty = 79.3364*sin(el) + 49.4663*cos(el) + 0.2188*temp + 2.25
  #pred_transx = -481.355*sin(el) - 245.984*cos(el) - 16.6192*temp + 228.33
  #pred_transy = -356.485*sin(el) + 1515.93*cos(el) + 115.356*temp + 154.46
  #pred_tiltx = 14.3645*sin(el) + 201.84*cos(el) + 0.08*temp + 346.0

  # from hecto 20060425
  #pred_tilty = 2.491*sin(el) + 30.789*cos(el) + 0.0*temp + 75.724
  #pred_transx = -107.026*sin(el) - 357.259*cos(el) - 0.0*temp - 58.504
  #pred_transy = 677.793*sin(el) + 2613.91*cos(el) + 0.0*temp - 1728.65
  #pred_tiltx = 24.519*sin(el) + 200.405*cos(el) + 0.0*temp + 277.78

  # megacam 20060629 (after f/5 cell fix)
  #pred_tilty = 2.491*sin(el) + 30.789*cos(el) + 0.0*temp + 110.724
  #pred_transx = -107.026*sin(el) - 357.259*cos(el) - 0.0*temp - 541.15
  #pred_transy = 677.793*sin(el) + 2613.91*cos(el) + 0.0*temp + 278.95
  #pred_tiltx = 24.519*sin(el) + 200.405*cos(el) + 0.0*temp + 260.78

  # 20060929 
  #pred_tilty = -12.97*sin(el) + 37.81*cos(el) + 0.0*temp + 86.21
  #pred_transx = 87.77*sin(el) - 400.79*cos(el) - 0.0*temp - 229.29
  #pred_transy = 708.92*sin(el) + 2179.76*cos(el) + 0.0*temp + 69.82
  #pred_tiltx = 33.73*sin(el) + 192.92*cos(el) + 0.0*temp + 255.92

  # 20061008
  pred_tilty = -12.97*sin(el) + 37.81*cos(el) + 0.0*temp + 104.0
  pred_transx = 87.77*sin(el) - 400.79*cos(el) - 0.0*temp - 367.6
  pred_transy = 708.92*sin(el) + 2179.76*cos(el) + 0.0*temp - 65.0
  pred_tiltx = 33.73*sin(el) + 192.92*cos(el) + 0.0*temp + 255.92

end

puts "We want to be at:" 
puts "   focus = #{pred_focus},"
puts "   tiltx = #{pred_tiltx},"
puts "   tilty = #{pred_tilty},"
puts "   transx = #{pred_transx},"
puts "   transy = #{pred_transy}"

focuserr = "%8.2f" % (pred_focus - focus)
tiltxerr = "%8.2f" % (pred_tiltx - tiltx)
tiltyerr = "%8.2f" % (pred_tilty - tilty)
transxerr = "%8.2f" % (pred_transx - transx)
transyerr = "%8.2f" % (pred_transy - transy)

puts "Moving hexapod:"
puts "   #{focuserr} um in focus,"
puts "   #{tiltxerr} arcsec in tiltx,"
puts "   #{tiltyerr} arcsec in tilty,"
puts "   #{transxerr} um in transx,"
puts "   #{transyerr} um in transy..."

msg_cmd(hexapod, 'focuserr', "#{focuserr}")
msg_cmd(hexapod, 'tiltxerr', "#{tiltxerr}")
msg_cmd(hexapod, 'tiltyerr', "#{tiltyerr}")
msg_cmd(hexapod, 'transxerr', "#{transxerr}")
msg_cmd(hexapod, 'transyerr', "#{transyerr}")

puts "Hexapod in motion......"

sleep(2)

loop do
  inmotion = msg_get(hexapod, 'motionFlag').to_i
  break if inmotion == 0
  sleep(1)
end

puts "Done."

hexapod.close
telserver.close
