#!/usr/bin/env tclsh
#

set env(WFS) .:9876
set count   1
set datadir /mmt/shwfs/datadir

set filename none
set filetime    0

source /mmt/scripts/msg.tcl

msg_server  WFS

msg_register WFS image

msg_publish  WFS filename filename
msg_publish  WFS filetime filetime

proc WFS.image { server sock msgid cmd size } {
    msg_ack $sock $msgid
    set filename "$::datadir/mmirs_wfs_[format %04d $::count].fits"
    incr ::count

    set file [open $filename w]
    fconfigure $sock -translation binary
    fconfigure $file -translation binary


    fcopy $sock $file -size $size
    close $file

    exec /mmt/shwfs/header.pl $filename 1.0 MMIRS

    set ::filename $filename
    set ::filetime [clock seconds]
}


msg_allow WFS "*"
msg_up    WFS

vwait forever

