# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded bob 1.0 [list source [file join $dir bob.tcl]]
package ifneeded camserv 1.0 [list source [file join $dir camserv.tcl]]
package ifneeded ljack 1.0 [list source [file join $dir ljack.tcl]]
package ifneeded maxim 1.0 [list source [file join $dir maxim.tcl]]\n[list source [file join $dir maxim.tcl]]
package ifneeded msg 1.0 [list source [file join $dir msg.tcl]]
package ifneeded pixelink 1.0 [list source [file join $dir pixelink.tcl]]
package ifneeded pmac 1.0 [list source [file join $dir pmac.tcl]]
package ifneeded pmacserv 1.0 [list source [file join $dir pmacserv.tcl]]
package ifneeded puntino 1.0 [list source [file join $dir puntino.tcl]]
package ifneeded sbig 1.0 [list source [file join $dir sbig.tcl]]
package ifneeded try 1.0 [list source [file join $dir try.tcl]]
package ifneeded viahm 1.0 [list source [file join $dir viahm.tcl]]
