#!/bin/sh
#

 mawk '
 BEGIN {
	indent = 0
	istar = "^((if)|(while)|(open))"
	iends = "^((endif)|(endwhile)|(close))"

	Indent[0] = ""
	for ( i = 1; i < 10; i++ )
		Indent[i] = Indent[i-1] " "
 }

 $0 ~ iends 	{ if ( indent ) indent--; 	}
 		{ print Indent[indent] $0	}
 $0 ~ istar && $0 !~ "wait" { 
		  indent++;			}
'
